language: python
sudo: required
python:
  - "2.6"
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev"  # 3.5 development branch
#  - "3.6"
#  - "3.6-dev"  # 3.6 development branch
#  - "3.7-dev"  # 3.7 development branch
#  - "nightly"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y openssl libcppunit-dev libreadline6 libreadline6-dev valgrind realpath libmodule-install-perl
    - wget https://github.com/torden/go-mdbm/raw/master/pkg/ubuntu/mdbm-Precise_Pangolin.deb
    - sudo dpkg -i mdbm-Precise_Pangolin.deb
    - sudo apt-get install -y gdb
    #- git clone https://github.com/yahoo/mdbm.git src_mdbm
before_script:
    - ulimit -c unlimited -S 
    - ulimit -s unlimited
script:
    - PYTHON=`which python` make
    - gdb `which python` core -batch -ex "bt full" \ -ex quit
